#!/usr/bin/env python3
"""Generate the appendix run table (sections/appendix_runs_table.tex).

Emits one longtable row per configuration in analysis/computer_vision_master_comparison.csv,
Gemini block first, then the open-weights (L-) block, each sorted by run id.
Regenerate with:  python analysis/computer_vision_make_appendix_table.py
"""
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
import outside_grid_runs  # noqa: E402  (prompt_baselines/ rows)

ROOT = Path(__file__).resolve().parent.parent
CSV = ROOT / "analysis" / "computer_vision_master_comparison.csv"
OUT = ROOT / "sections" / "appendix_runs_table.tex"


def prompt_flags(row) -> str:
    """Compact prompt-component string: S solution, G guidelines, B breakdown,
    R thinking/reasoning on, F few-shot."""
    s = ""
    if row.use_solution:
        s += "S"
    if row.use_guidelines:
        s += "G"
    if row.use_breakdown:
        s += "B"
    if row.use_reasoning:
        s += "R"
    if row.few_shot:
        s += "F"
    return s if s else "---"


def tex_escape(s: str) -> str:
    return s.replace("_", r"\_")


def fmt_t(t: float) -> str:
    return "0" if t == 0 else f"{t:.1f}"


def main() -> None:
    df = pd.read_csv(CSV)
    closed = df[df.source != "local"].sort_values("run_id")   # Gemini (Vertex), OpenAI (O), Anthropic (N)
    loc = df[df.source == "local"].sort_values("run_id")
    n_src = closed.source.value_counts()
    extra = outside_grid_runs.prompt_baseline_rows()

    lines = [
        "% Auto-generated by analysis/computer_vision_make_appendix_table.py -- do not edit by hand.",
        r"\begingroup",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{2.5pt}",
        r"\setlength{\LTcapwidth}{\linewidth}",
        r"\begin{longtable}{llllcrrcrl}",
        r"\caption{Every grader configuration in the study, one row per run:"
        rf" the ${len(closed)}$ closed-model configurations (${n_src.get('gemini', 0)}$ Gemini via Vertex,"
        rf" ${n_src.get('openai', 0)}$ OpenAI and ${n_src.get('anthropic', 0)}$ Anthropic via their batch APIs;"
        r" Section~\ref{sec:closed:vendors}) followed by the"
        rf" ${len(loc)}$ open-weights (L-) configurations, each sorted by run id. "
        r"\emph{Prompt} lists the"
        r" components present (S~reference solution, G~grading guidelines,"
        r" B~rubric breakdown, R~thinking enabled, F~few-shot demonstrations);"
        r" personas prefixed \texttt{mp} are the mechanism probes of"
        r" Section~\ref{sec:brittle:attrib}: \texttt{mpstrict}, \texttt{mprigorous} and"
        r" \texttt{mpfair} keep the \emph{strict} preset's two policy sentences and swap"
        r" only its headword; \texttt{mpframe} is the HARSH frame alone, \texttt{mpnoclause}"
        r" the frame with S1, \texttt{mps2only} the frame with S2, \texttt{mpharsh} the frame"
        r" with both (the \emph{strict} text, rerun on the current stack); \texttt{mpnharsh}"
        r" is the neutral frame with ``harsh'' in place of ``strict''. L-MP$04$ and L-PS$03$ are one physical run"
        r" (\texttt{qwen2.5-coder-32b}, \emph{mpnoclause}), listed under both the headword"
        r" series and the policy $2\times2$. $n$ is the number of students"
        r" scored against the grader average; MAE and bias are on the $35$-point"
        r" base scale, the $95\%$ bootstrap CI on MAE; behaviour classes are defined"
        r" in Section~\ref{sec:brittle:numbers}. A refusal's MAE is a ceiling"
        r" artifact, not a severity measurement. D$03$ ran with thinking active"
        r" regardless of its flag (\texttt{gemini-2.5-pro} cannot disable it;"
        r" Appendix~\ref{app:details}). \texttt{claude-opus-5} exposes no sampling"
        r" temperature (thinking disabled; shown as ---). The final block lists the"
        rf" ${len(extra)}$ prompt-only baselines of Appendix~\ref{{app:promptbaselines}}"
        r" (first $100$ students; the persona column names the strategy), which are"
        r" not configurations of the paper's grader and are excluded from every count;"
        r" their CIs use $2000$ resamples. Model keys match the released"
        r" spreadsheets. Generated by \texttt{analysis/computer\_vision\_make\_appendix\_table.py}.}"
        r"\label{tab:allruns}\\",
        r"\toprule",
        r"Run & Model & Persona & Prompt & $t$ & $n$ & MAE & $95\%$ CI & Bias & Behaviour \\",
        r"\midrule",
        r"\endfirsthead",
        r"\multicolumn{10}{l}{\emph{Table~\ref{tab:allruns} continued}}\\",
        r"\toprule",
        r"Run & Model & Persona & Prompt & $t$ & $n$ & MAE & $95\%$ CI & Bias & Behaviour \\",
        r"\midrule",
        r"\endhead",
        r"\bottomrule",
        r"\endfoot",
    ]

    def block(rows, title):
        out = [rf"\multicolumn{{10}}{{l}}{{\emph{{{title}}}}}\\*"]
        for row in rows.itertuples():
            out.append(
                " & ".join(
                    [
                        tex_escape(row.run_id),
                        rf"\texttt{{{tex_escape(row.model)}}}",
                        tex_escape(row.strictness),
                        prompt_flags(row),
                        "---" if str(row.model).startswith("claude") else f"${fmt_t(row.temperature)}$",
                        f"${row.n_valid_vs_TA:.0f}$",
                        f"${row.MAE_vs_TA_avg:.2f}$",
                        f"$[{row.MAE_CI95_lo:.2f},\\ {row.MAE_CI95_hi:.2f}]$",
                        f"${row.bias_vs_TA_avg:+.2f}$",
                        tex_escape(row.behaviour),
                    ]
                )
                + r" \\"
            )
        return out

    lines += block(closed, "Closed-model configurations (Gemini: A--P series; OpenAI: O; Anthropic: N)")
    lines.append(r"\midrule")
    lines += block(loc, "Open-weights (L-) configurations")
    lines.append(r"\midrule")
    lines.append(r"\multicolumn{10}{l}{\emph{Prompt-only baselines (Appendix~\ref{app:promptbaselines}; not grader configurations)}}\\*")
    lines += outside_grid_runs.tex_rows(extra, tex_escape)
    lines += [r"\end{longtable}", r"\endgroup"]

    OUT.parent.mkdir(parents=True, exist_ok=True)   # sections/ does not ship
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(closed)} closed + {len(loc)} local + {len(extra)} prompt-baseline rows)")


if __name__ == "__main__":
    main()
