#!/usr/bin/env python3
"""Generate the second-exam appendix run table (sections/introduction_to_ai_appendix_runs_table.tex).

Emits one longtable row per configuration in analysis/introduction_to_ai_master_comparison.csv,
Gemini (IG-) block first, then the open-weights (IA-) block, each in run-id order --
the Stage 2 counterpart of computer_vision_make_appendix_table.py, with the same
columns so the two tables read identically.

Regenerate with:  python analysis/introduction_to_ai_make_appendix_table.py
(the CSV itself is regenerated by analysis/introduction_to_ai_run_analysis.py).
"""
import re
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
CSV = ROOT / "analysis" / "introduction_to_ai_master_comparison.csv"
OUT = ROOT / "sections" / "introduction_to_ai_appendix_runs_table.tex"


def prompt_flags(row) -> str:
    """Compact prompt-component string: S solution, G guidelines, B breakdown,
    R thinking/reasoning on, F few-shot. This exam has no guidelines document,
    so G is structurally absent from every row."""
    s = ""
    if row.use_solution:
        s += "S"
    if row.use_guidelines:
        s += "G"
    if row.use_breakdown:
        s += "B"
    if row.use_reasoning:
        s += "R"
    if row.few_shot:
        s += "F"
    return s if s else "---"


def tex_escape(s: str) -> str:
    return s.replace("_", r"\_")


def fmt_t(t: float) -> str:
    return "0" if t == 0 else f"{t:.1f}"


def run_sort_key(rid: str):
    """Natural order: IA01-Q7-n < IA02-Q32-s < IA11 < IA106 < IA201."""
    m = re.match(r"^(I[AGNO])(\d+)(.*)$", rid)
    if not m:
        return (rid, 0, "")
    return (m.group(1), int(m.group(2)), m.group(3))


def behaviour_short(b: str) -> str:
    """The CSV annotates refusals with their zero-rate; the table keeps the class."""
    return str(b).split(" (")[0]


def main() -> None:
    df = pd.read_csv(CSV)
    df["_k"] = df.run_id.map(run_sort_key)
    closed = df[df.source != "local"].sort_values("_k")   # Gemini (IG), OpenAI (IO), Anthropic (IN)
    loc = df[df.source == "local"].sort_values("_k")
    n_src = closed.source.value_counts()

    lines = [
        "% Auto-generated by analysis/introduction_to_ai_make_appendix_table.py -- do not edit by hand.",
        r"\begingroup",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{2.5pt}",
        r"\setlength{\LTcapwidth}{\linewidth}",
        r"\begin{longtable}{llllcrrcrl}",
        r"\caption{Every second-exam grader configuration, one row per run: the"
        rf" ${len(closed)}$ closed-model configurations (${n_src.get('gemini', 0)}$ Gemini IG-,"
        rf" ${n_src.get('openai', 0)}$ OpenAI IO- and ${n_src.get('anthropic', 0)}$ Anthropic IN-;"
        rf" Section~\ref{{sec:closed:vendors}}) followed by the ${len(loc)}$"
        r" open-weights (IA-) configurations, each in run-id order. \emph{Prompt}"
        r" lists the components present (S~reference solution, B~rubric breakdown,"
        r" R~thinking enabled, F~few-shot demonstrations); this exam has no"
        r" student-facing guidelines document, so the G component of"
        r" Table~\ref{tab:allruns} never appears. Personas prefixed \texttt{mp}"
        r" are the mechanism probes of Section~\ref{sec:brittle:attrib}, replayed"
        r" on this exam (keys decoded in Table~\ref{tab:allruns}'s caption). $n$ is the number of students scored against the grader"
        r" average ($\ast$: IG$18$'s $693$ are the survivors of prompt-length failures, an"
        r" easier subsample whose MAE is not comparable to full-cohort rows;"
        r" Appendix~\ref{app:replication}); MAE and bias are on the $\approx 65$-point scale (score plus"
        r" bonus, matching how its graders record marks), the $95\%$ bootstrap CI"
        r" (\num{50000} resamples) on MAE. Behaviour classes are those of"
        r" Section~\ref{sec:brittle:numbers}, at this exam's floor-matched collapse band"
        r" ($\text{MAE} \ge 15.7$), and describe a run's error level rather than persona"
        r" damage: DeepSeek-Coder-V2-Lite over-marks badly enough to leave it unprompted"
        r" (IA$11$, IA$13$). A refusal's"
        r" MAE is a ceiling artifact, not a severity measurement. IG$15$--IG$20$"
        r" ran on the first $100$ students; IG$10$--IG$12$, IA$92$ and IA$136$ are"
        r" repeated-sampling probes whose scores are the per-student mean across"
        r" five reruns (Appendix~\ref{app:replication}). \texttt{claude-opus-5} exposes"
        r" no sampling temperature (thinking disabled; shown as ---). Run ids match the"
        r" released tracker and spreadsheets. Generated by"
        r" \texttt{analysis/introduction\_to\_ai\_make\_appendix\_table.py}.}"
        r"\label{tab:iaruns}\\",
        r"\toprule",
        r"Run & Model & Persona & Prompt & $t$ & $n$ & MAE & $95\%$ CI & Bias & Behaviour \\",
        r"\midrule",
        r"\endfirsthead",
        r"\multicolumn{10}{l}{\emph{Table~\ref{tab:iaruns} continued}}\\",
        r"\toprule",
        r"Run & Model & Persona & Prompt & $t$ & $n$ & MAE & $95\%$ CI & Bias & Behaviour \\",
        r"\midrule",
        r"\endhead",
        r"\bottomrule",
        r"\endfoot",
    ]

    def block(rows, title):
        out = [rf"\multicolumn{{10}}{{l}}{{\emph{{{title}}}}}\\*"]
        for row in rows.itertuples():
            out.append(
                " & ".join(
                    [
                        tex_escape(row.run_id),
                        rf"\texttt{{{tex_escape(row.model)}}}",
                        tex_escape(row.strictness),
                        prompt_flags(row),
                        "---" if str(row.model).startswith("claude") else f"${fmt_t(row.temperature)}$",
                        f"${row.n_valid_vs_TA:.0f}$" + (r"$^{\ast}$" if row.run_id == "IG18" else ""),
                        f"${row.MAE_vs_TA_avg:.2f}$",
                        f"$[{row.MAE_CI95_lo:.2f},\\ {row.MAE_CI95_hi:.2f}]$",
                        f"${row.bias_vs_TA_avg:+.2f}$",
                        tex_escape(behaviour_short(row.behaviour)),
                    ]
                )
                + r" \\"
            )
        return out

    lines += block(closed, "Closed-model configurations (Gemini IG-, OpenAI IO-, Anthropic IN-)")
    lines.append(r"\midrule")
    lines += block(loc, "Open-weights (IA-) configurations")
    lines += [r"\end{longtable}", r"\endgroup"]

    OUT.parent.mkdir(parents=True, exist_ok=True)   # sections/ does not ship
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(closed)} closed + {len(loc)} local rows)")


if __name__ == "__main__":
    main()
